import { ICubeDirection } from './cube/CubeDirection';
import { ICubeEventListener } from './cube/CubeEventListener';
import { ICubeMoveMatrix } from './cube/CubeMoveMatrix';
import { ICubeMovement } from './cube/CubeMovement';
import { IDegreePositionChooser } from './cube/mutation/DegreePositionChooser';
import { IFinalPositionFinder } from './cube/mutation/FinalPositionFinder';
import { IMatrixValueChooser } from './cube/mutation/MatrixValueChooser';
import { IMutationApi } from './cube/mutation/MutationApi';
import { IPercentagePositionChooser } from './cube/mutation/PercentagePositionChooser';
import { IViewport } from './cube/Viewport';
import { ICubeUtils } from './utils/CubeUtils';
import { IEventListenerMap } from './utils/EventListenerMap';
export declare const CUBE_DIRECTION: import("@airport/direction-indicator").IDependencyInjectionToken<ICubeDirection>;
export declare const CUBE_EVENT_LISTENER: import("@airport/direction-indicator").IDependencyInjectionToken<ICubeEventListener>;
export declare const CUBE_MOVE_MATRIX: import("@airport/direction-indicator").IDependencyInjectionToken<ICubeMoveMatrix>;
export declare const CUBE_MOVEMENT: import("@airport/direction-indicator").IDependencyInjectionToken<ICubeMovement>;
export declare const CUBE_UTILS: import("@airport/direction-indicator").IDependencyInjectionToken<ICubeUtils>;
export declare const DEGREE_POSITION_CHOOSER: import("@airport/direction-indicator").IDependencyInjectionToken<IDegreePositionChooser>;
export declare const EVENT_LISTENER_MAP: import("@airport/direction-indicator").IDependencyInjectionToken<IEventListenerMap>;
export declare const FINAL_POSITION_FINDER: import("@airport/direction-indicator").IDependencyInjectionToken<IFinalPositionFinder>;
export declare const MATRIX_VALUE_CHOOSER: import("@airport/direction-indicator").IDependencyInjectionToken<IMatrixValueChooser>;
export declare const MUTATION_API: import("@airport/direction-indicator").IDependencyInjectionToken<IMutationApi>;
export declare const PERCENTAGE_POSITION_CHOOSER: import("@airport/direction-indicator").IDependencyInjectionToken<IPercentagePositionChooser>;
export declare const VIEWPORT: import("@airport/direction-indicator").IDependencyInjectionToken<IViewport>;
//# sourceMappingURL=tokens.d.ts.map