export const ABOUT = '/about';
export const FEEDBACK = '/feedback';
export const RELEASE_PLAN = '/releasePlan';
export const FACTOR_INFO_MAIN = '/factor/info/Main/:mode';
export const FACTOR_LIST = '/factor/List';
export const IDEA_LIST = '/idea/List';
export const DERIVATION_LIST = '/derivation/List/:repositoryUuId';
export const IDEA_FORM = '/idea/Form/:mode/:hostingPlatform/:repositoryUuId';
export const IDEA_FORUM = '/idea/Forum/:mode/:hostingPlatform/:repositoryUuId/:forumHostingPlatform/:forumRepositoryUuId/';
export const IDEA_MAIN = '/idea/Main/:mode/:hostingPlatform/:repositoryUuId';
export const IDEA_LOCATIONS = '/idea/Locations/:mode';
export const IDEA_TIME_FRAME = '/idea/TimeFrame/:mode';
export const CARD_CLIMATE_CHANGE = '/card/ClimateChange';
//# sourceMappingURL=routing.js.map