import { IIdeaConverter } from './converter/IdeaConverter';
import { ILogicUtils } from './LogicUtils';
import { IDetailedCubeLogic } from './pages/components/idea/DetailedCubeLogic';
import { IFactorRankingLogic } from './pages/idea/info/FactorRankingLogic';
import { IIdeaFormLogic } from './pages/idea/info/IdeaFormLogic';
import { IIdeaMainLogic } from './pages/idea/info/IdeaMainLogic';
import { IIdeaFormManager } from './pages/idea/IdeaFormManager';
import { ICubeLogic } from './idea/CubeLogic';
import { IIdeaManager } from './idea/IdeaManager';
import { IAgreementManager } from './idea/AgreementManager';
import { IAgreementConverter } from './converter/AgreementConverter';
export declare const AGREEMENT_CONVERTER: import("@airport/direction-indicator").IDependencyInjectionToken<IAgreementConverter>;
export declare const AGREEMENT_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IAgreementManager>;
export declare const CUBE_LOGIC: import("@airport/direction-indicator").IDependencyInjectionToken<ICubeLogic>;
export declare const DETAILED_CUBE_LOGIC: import("@airport/direction-indicator").IDependencyInjectionToken<IDetailedCubeLogic>;
export declare const FACTOR_RANKING_LOGIC: import("@airport/direction-indicator").IDependencyInjectionToken<IFactorRankingLogic>;
export declare const IDEA_CONVERTER: import("@airport/direction-indicator").IDependencyInjectionToken<IIdeaConverter>;
export declare const IDEA_FORM_LOGIC: import("@airport/direction-indicator").IDependencyInjectionToken<IIdeaFormLogic>;
export declare const IDEA_FORM_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IIdeaFormManager>;
export declare const IDEA_MAIN_LOGIC: import("@airport/direction-indicator").IDependencyInjectionToken<IIdeaMainLogic>;
export declare const IDEA_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IIdeaManager>;
export declare const LOGIC_UTILS: import("@airport/direction-indicator").IDependencyInjectionToken<ILogicUtils>;
//# sourceMappingURL=tokens.d.ts.map