import { diToken } from '@airport/di';
export const AJAX_Z_CONTINENT = diToken();
export const AJAX_Z_COUNTRY = diToken();
export const AJAX_Z_COUNTY = diToken();
export const AJAX_Z_FACTOR = diToken();
export const AJAX_Z_FACTOR_POSITION = diToken();
export const AJAX_Z_POSITION = diToken();
export const AJAX_Z_POLL = diToken();
export const AJAX_Z_POLL_CONTINENT = diToken();
export const AJAX_Z_POLL_COUNTRY = diToken();
export const AJAX_Z_POLL_COUNTY = diToken();
export const AJAX_Z_POLL_LABEL = diToken();
export const AJAX_Z_POLL_STATE = diToken();
export const AJAX_Z_POLL_TOWN = diToken();
export const AJAX_Z_LABEL = diToken();
export const AJAX_Z_POLL_FACTOR_POSITION = diToken();
export const AJAX_Z_STATE = diToken();
export const AJAX_Z_TOWN = diToken();
//# sourceMappingURL=tokens.js.map