"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const di_1 = require("@airport/di");
exports.AJAX_Z_CONTINENT = di_1.diToken();
exports.AJAX_Z_COUNTRY = di_1.diToken();
exports.AJAX_Z_COUNTY = di_1.diToken();
exports.AJAX_Z_FACTOR = di_1.diToken();
exports.AJAX_Z_FACTOR_POSITION = di_1.diToken();
exports.AJAX_Z_POSITION = di_1.diToken();
exports.AJAX_Z_POLL = di_1.diToken();
exports.AJAX_Z_POLL_CONTINENT = di_1.diToken();
exports.AJAX_Z_POLL_COUNTRY = di_1.diToken();
exports.AJAX_Z_POLL_COUNTY = di_1.diToken();
exports.AJAX_Z_POLL_LABEL = di_1.diToken();
exports.AJAX_Z_POLL_STATE = di_1.diToken();
exports.AJAX_Z_POLL_TOWN = di_1.diToken();
exports.AJAX_Z_LABEL = di_1.diToken();
exports.AJAX_Z_POLL_FACTOR_POSITION = di_1.diToken();
exports.AJAX_Z_STATE = di_1.diToken();
exports.AJAX_Z_TOWN = di_1.diToken();
//# sourceMappingURL=tokens.js.map